kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-irods-service
spec:
  selector:
    app: {{ .Release.Name }}-irods
  ports:
  {{- toYaml .Values.service.ports | nindent 2 }}
  type: {{ .Values.service.type }}