apiVersion: apps/v1 
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -c
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  name: {{ .Release.Name }}-irods
  labels:
    app: {{ .Release.Name }}-irods
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.cockroachdb.Replicas }}
  {{- end }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Release.Name }}-irods
    spec:
      containers:
      - image: {{ .Values.docker.repo }}/{{ .Values.imageTag }}
        name: {{ .Release.Name }}-irods
        ports:
        - containerPort: 1247
        - containerPort: 1248
      - env: &env1
        - name: IRODS_DATABASE_NAME
          value: {{ .Values.cockroachdbDatabase }}
        - name: GID_IRODS
          value: {{ quote .Values.GID_IRODS }}
        - name: IRODS_DATABASE_PASSWORD
          value: {{ .Values.cockroachdbPassword }}
        - name: IRODS_DATABASE_SERVER_HOSTNAME
          value: {{ .Release.Name }}-cockroachdb
        - name: IRODS_DATABASE_USER_NAME
          value: {{ .Values.cockroachdbUser }}
        - name: IRODS_HOST
          value: {{ .Release.Name }}-irods-local-dev
        - name: IRODS_SERVER_ADMINISTRATOR_PASSWORD
          value: {{ .Values.IRODS_SERVER_ADMINISTRATOR_PASSWORD }}
        - name: IRODS_SERVER_ADMINISTRATOR_USER_NAME
          value: {{ .Values.IRODS_SERVER_ADMINISTRATOR_USER_NAME }}
        - name: IRODS_SERVER_ROLE
          value: {{ quote .Values.IRODS_SERVER_ROLE }}
        - name: IRODS_ZONE_NAME
          value: {{ .Values.IRODS_ZONE_NAME }}
        - name: UID_IRODS
          value: {{ quote .Values.UID_IRODS }}
        {{- range $key, $value := .Values.environment.variables }}
        - name: {{ $key }}
          value: {{ $value }}
        {{- end }}
        volumeMounts:
          {{- toYaml .Values.volumeMounts.variables | nindent 10 }}
      initContainers:
      - env: *env1
      - image: {{ .Values.docker.repo }}/{{ .Values.imageTag }}
        name: init-irods
        args: ["init"]
        volumeMounts:
          {{- toYaml .Values.initVolumeMounts.variables | nindent 10 }}
      volumes:
      - name: data
        {{- if .Values.volumes.persistentVolumeClaim.enabled }}
      	persistentVolumeClaim:
	        claimName: {{ .Values.data }}
        {{- else }}
        hostPath:
          Path: C:\Users\Admin\Desktop\tmp
        {{- end }}
      {{- toYaml .Values.volumes.variables | nindent 6 }}
      hostname: {{ .Release.Name }}-irods-local-dev
      restartPolicy: Always
