{{- if .Values.volumes.persistentVolumeClaim.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-{{ .Values.event_handler }}
{{- toYaml .Values.spec | nindent 12 }}
{{- end }}