{{- if .Values.service.enabled }}
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-irods-capability-automated-ingest-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-irods-capability-automated-ingest
  ports:
    {{- toYaml .Values.service.ports | nindent 4 }}
{{- end }}
