# Default values for irods.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

postgresql:
  postgresUser: irods
  postgresPassword: testpassword
  postgresDatabase: ICAT
  replica: 1


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

IRODS_SERVER_ADMINISTRATOR_PASSWORD: rods
IRODS_SERVER_ADMINISTRATOR_USER_NAME: rods
IRODS_ZONE_NAME: tempZone
IRODS_SERVER_ROLE: 1
GID_IRODS: 998
UID_IRODS: 998
data: /host/data
irods: irods-postgresql
POST_GRESQL: postgresql
irods_local_dev: irods-local-dev
image: irods-provider-postgresql:4.2.2
initImageName: init-irods

environment:
  variables:
    IRODS_CONTROL_PLANE_KEY: TEMPORARY__32byte_ctrl_plane_key
    IRODS_CONTROL_PLANE_PORT: '"1248"'
    IRODS_DATABASE_SERVER_PORT: '"5432"'
    IRODS_DATABASE_USER_PASSWORD_SALT: tempsalt
    IRODS_PORT: '"1247"'
    IRODS_PORT_RANGE_BEGIN: '"20000"'
    IRODS_PORT_RANGE_END: '"20199"'
    IRODS_SCHEMA_VALIDATION: file:///var/lib/irods/configuration_schemas
    IRODS_SERVER_NEGOTIATION_KEY: TEMPORARY_32byte_negotiation_key
    IRODS_SERVER_ZONE_KEY: TEMPORARY_zone_key
    IRODS_SERVICE_ACCOUNT_NAME: irods
    IRODS_SERVICE_ACCOUNT_GROUP: irods
    IRODS_VAULT_DIRECTORY: /var/lib/irods/iRODS/Vault
    ODBC_DRIVER_FOR_POSTGRES: '"2"'
  initContainerEnv:
    IRODS_CONTROL_PLANE_KEY: TEMPORARY__32byte_ctrl_plane_key
    IRODS_CONTROL_PLANE_PORT: '"1248"'
    IRODS_DATABASE_SERVER_PORT: '"5432"'
    IRODS_DATABASE_USER_PASSWORD_SALT: tempsalt
    IRODS_PORT: '"1247"'
    IRODS_PORT_RANGE_BEGIN: '"20000"'
    IRODS_PORT_RANGE_END: '"20199"'
    IRODS_SCHEMA_VALIDATION: file:///var/lib/irods/configuration_schemas
    IRODS_SERVER_NEGOTIATION_KEY: TEMPORARY_32byte_negotiation_key
    IRODS_SERVER_ZONE_KEY: TEMPORARY_zone_key
    IRODS_SERVICE_ACCOUNT_NAME: irods
    IRODS_VAULT_DIRECTORY: /var/lib/irods/iRODS/Vault
    ODBC_DRIVER_FOR_POSTGRES: '"2"'
    IRODS_SERVICE_ACCOUNT_GROUP: irods

volumeMounts:
  variables:
  - name: data
    mountPath: /data
  - name: varlibirods
    mountPath: /var/lib/irods
  - name: etcirods
    mountPath: /etc/irods

initVolumeMounts:
  variables:
  - name: varlibirods
    mountPath: /var/lib/irods
  - name: etcirods
    mountPath: /etc/irods

service:
  ports:
    - protocol: TCP
      port: 1247
      targetPort: 1247
      name: data-plane
    - protocol: TCP
      port: 1248
      targetPort: 1248
      name: control-plane
  type: ClusterIP 